export * from './canonicalizer.js'
export * from './descriptor.js'
export * from './merger.js'
export * from './errors.js'
export type { Workspace, WorkspaceManifest, WorkspaceLanguage, WorkspaceErrorInfo } from './workspace-types.js'
export { detectWorkspaces, _resetMemoCache } from './detect-workspaces.js'
